### ISSUE TITLE
Randomization value still visible post allocation

### ISSUE THREAD

**Issue by champmcnair** [vanderbilt-redcap/hide-randomization-values-module#1]
We are able to see the allocated randomization value with the module in place on projects where the randomization field is a dropdown type.  Radio fields work as expected.  RC v9.1.9 tested in Firefox and Chrome

**Comment by mmcev106** [comment]
@champmcnair, thanks very much for reporting this!  I just released 1.0.2 which should support dropdowns.  I'll go ahead and close this, but feel free to reopen it if you encounter any issues.
