### ISSUE TITLE
Does not work with a mobile device

### ISSUE THREAD

**Issue by 274188A** [vanderbilt-redcap/hide-randomization-values-module#4]
We found that if a researcher uses a mobile phone, the EM does not hide the randomized value.
![original-9801E8DE-B31D-4963-AA6D-19E3DF03B3F6](https://github.com/vanderbilt-redcap/hide-randomization-values-module/assets/40014477/fda7b29e-b389-4fa0-bfff-14c374ccd445)

**Comment by mmcev106** [comment]
@274188A, version 1.0.5 should fix this.  See [this comment](https://redcap.vanderbilt.edu/community/post.php?id=221832&comment=223806) for details.
