### ISSUE TITLE
Randomization patient allocation group list not hidden in old Google Chrome browser version

### ISSUE THREAD

**Issue by LouisLalonde** [vanderbilt-redcap/hide-randomization-values-module#6]
**Tested on**

1. Google Chrome version 91.0.4472.77
3. REDCap version 14.0.21
4. Hide Randomization Values - v1.0.5

**Issue**

The REDCap randomization patient allocation group list used to display the patient allocation group is not hidden at any moment from the user. A user accessing the randomization form can immediately determine the patient allocation group label.

**See the following picture**

![hide-randomization-values-module rand list not hidden](https://github.com/vanderbilt-redcap/hide-randomization-values-module/assets/74996931/51dc93b7-6a75-4b09-856b-dae6899d0576)

This is a critical issue since this could lead to protocol violations, patient assessment and treatment bias.

**Steps to reproduce**:

1. Enable the Hide Randomization Values external module
2. Randomized a patient

This issue is mitigated by updating Google Chrome to a more recent version. However, research personnel often use their institution personal workstation which often has fixed and outdated software version. Additionally, they don't have any control over the software version they are using and neither do they have the possibility to update them.

This issue is not observed on older Microsoft Edge version. e. g. 109.0.1518.140.

Louis Lalonde
University of Montreal Health Centre (CHUM)

**Comment by mmcev106** [comment]
That version of Chrome is more than two years old, and has all kinds of published vulnerabilities at this point.  I believe updating Chrome is the appropriate action.  Even if this module had an active support budget, using it on supporting outdated browser versions would not be a priority.  Closing...
